/**
 * Sprint 1 — order model + state machine.
 *
 * Invariant: an order can never reach FILLED without fill accounting; every
 * transition below is explicit and invalid transitions are rejected.
 */

export const ORDER_STATUSES = [
  "PENDING", // created locally, not sent to a venue yet
  "SUBMITTED", // accepted by the venue, no fills yet
  "PARTIALLY_FILLED",
  "FILLED",
  "CANCELLING",
  "CANCELLED",
  "REJECTED",
  "FAILED",
  "EXPIRED",
] as const;

export type OrderStatus = (typeof ORDER_STATUSES)[number];

export type OrderSide = "UP" | "DOWN";
export type OrderType = "LIMIT" | "MARKET";
export type ExecutionMode = "paper" | "backtest" | "shadow" | "live";

export interface BookLevel {
  price: number;
  shares: number;
}

export interface Fill {

  /** Venue-supplied (or deterministic) id — used for idempotent application. */
  fillId: string;
  price: number;
  shares: number;
  fee: number;
  filledAt: string;
}

export interface Order {
  id: string;
  /** Idempotency key generated by the caller before the order is sent. */
  clientOrderId: string;
  venueOrderId: string | null;
  market: string;
  side: OrderSide;
  orderType: OrderType;
  mode: ExecutionMode;
  /** Limit price; for MARKET orders this is the reference/expected price. */
  price: number;
  sizeShares: number;
  filledShares: number;
  avgFillPrice: number;
  feesPaid: number;
  status: OrderStatus;
  reason: string | null;
  error: string | null;
  createdAt: string;
  updatedAt: string;
  fills: Fill[];
}

const TRANSITIONS: Record<OrderStatus, readonly OrderStatus[]> = {
  PENDING: ["SUBMITTED", "REJECTED", "FAILED", "CANCELLED"],
  SUBMITTED: ["PARTIALLY_FILLED", "FILLED", "CANCELLING", "CANCELLED", "REJECTED", "FAILED", "EXPIRED"],
  PARTIALLY_FILLED: ["PARTIALLY_FILLED", "FILLED", "CANCELLING", "CANCELLED", "FAILED", "EXPIRED"],
  CANCELLING: ["CANCELLED", "PARTIALLY_FILLED", "FILLED", "FAILED"],
  FILLED: [],
  CANCELLED: [],
  REJECTED: [],
  FAILED: [],
  EXPIRED: [],
};

export const TERMINAL_STATUSES: readonly OrderStatus[] = [
  "FILLED",
  "CANCELLED",
  "REJECTED",
  "FAILED",
  "EXPIRED",
];

export function isTerminal(status: OrderStatus): boolean {
  return TERMINAL_STATUSES.includes(status);
}

export function canTransition(from: OrderStatus, to: OrderStatus): boolean {
  return TRANSITIONS[from].includes(to);
}

export class InvalidTransitionError extends Error {
  constructor(
    readonly from: OrderStatus,
    readonly to: OrderStatus,
  ) {
    super(`Invalid order transition ${from} -> ${to}`);
    this.name = "InvalidTransitionError";
  }
}

export function assertTransition(from: OrderStatus, to: OrderStatus): void {
  if (!canTransition(from, to)) throw new InvalidTransitionError(from, to);
}

export function remainingShares(order: Order): number {
  return Math.max(0, round6(order.sizeShares - order.filledShares));
}

export function notionalUsd(order: Order): number {
  return round6(order.sizeShares * order.price);
}

export function round6(n: number): number {
  return Math.round(n * 1e6) / 1e6;
}
