import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { ArrowDownRight, ArrowUpRight, Minus } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ChartContainer, ChartTooltip, ChartTooltipContent } from "@/components/ui/chart";
import { Area, Bar, CartesianGrid, ComposedChart, Line, XAxis, YAxis } from "recharts";
import { analyticsQueryKeys, getFeatureImportance, getVolatility, type MarketSnapshotRow } from "@/lib/riskApi";

export function MarketSnapshot({ markets }: { markets: MarketSnapshotRow[] }) {
  const [category, setCategory] = useState("all");
  const visible = category === "all" ? markets : markets.filter((m) => m.category === category);
  const categories = [...new Set(markets.map((m) => m.category))];
  return <section className="panel overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-4 py-3"><div><div className="label-caps">Markets snapshot</div><p className="tape mt-1 text-xs text-muted-foreground">live signal surface · {visible.length} markets</p></div><Select value={category} onValueChange={setCategory}><SelectTrigger className="w-36"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All categories</SelectItem>{categories.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead><tr className="label-caps border-b border-border text-left"><th className="px-4 py-3">Market</th><th>Category</th><th>Price</th><th>ML signal</th><th>Confidence</th><th className="text-right">Open P&L</th></tr></thead><tbody>{visible.map((market) => { const signal = market.ml_signal; const Icon = signal === "BUY" ? ArrowUpRight : signal === "SELL" ? ArrowDownRight : Minus; return <tr key={market.slug} className="border-b border-border/60 last:border-0"><td className="max-w-[260px] truncate px-4 py-3 font-medium" title={market.slug}>{market.slug}</td><td><Badge variant="outline">{market.category}</Badge></td><td className="tape">{market.price == null ? "—" : `$${market.price.toFixed(3)}`}</td><td><span className={`tape inline-flex items-center gap-1 ${signal === "BUY" ? "text-up" : signal === "SELL" ? "text-down" : "text-muted-foreground"}`}><Icon className="size-4" aria-hidden />{signal}</span></td><td className="w-40"><div className="flex items-center gap-2"><Progress value={market.confidence * 100} className="h-1.5" /><span className="tape text-[10px]">{(market.confidence * 100).toFixed(0)}%</span></div></td><td className={`tape px-4 text-right ${market.open_pnl != null && market.open_pnl >= 0 ? "text-up" : "text-down"}`}>{market.open_pnl == null ? "—" : `${market.open_pnl >= 0 ? "+" : ""}$${market.open_pnl.toFixed(2)}`}</td></tr> })}</tbody></table></div></section>;
}

export function FeatureImportancePanel() {
  const [model, setModel] = useState("default");
  const query = useQuery({ queryKey: analyticsQueryKeys.featureImportance(model), queryFn: () => getFeatureImportance(model), staleTime: 30_000 });
  const models = query.data?.models ?? [];
  return <PanelShell title="Feature importance heatmap" hint="SHAP attribution"><div className="mb-4 max-w-xs"><Select value={model} onValueChange={setModel}><SelectTrigger><SelectValue placeholder="Select model" /></SelectTrigger><SelectContent><SelectItem value="default">Default model</SelectItem>{models.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div><ChartContainer config={{ shap_value: { label: "SHAP", color: "var(--color-primary)" } }} className="h-[320px] w-full"><ComposedChart data={query.data?.features ?? []} layout="vertical" margin={{ left: 16, right: 20 }}><CartesianGrid horizontal={false} /><XAxis type="number" tickFormatter={(v) => Number(v).toFixed(2)} /><YAxis dataKey="feature" type="category" width={110} tickLine={false} axisLine={false} /><ChartTooltip content={<ChartTooltipContent />} /><Bar dataKey="shap_value" radius={3} fill="var(--color-primary)" /></ComposedChart></ChartContainer></PanelShell>;
}

export function VolatilityPanel({ marketSlug }: { marketSlug: string }) { const query = useQuery({ queryKey: analyticsQueryKeys.volatility(marketSlug, 7), queryFn: () => getVolatility(marketSlug, 7), enabled: Boolean(marketSlug), staleTime: 30_000 }); return <PanelShell title="Rolling volatility & momentum" hint={query.data ? `${query.data.category} · 7D` : "analytics API"}><ChartContainer config={{ price: { label: "Price", color: "var(--color-accent)" }, volatility: { label: "Volatility", color: "var(--color-primary)" }, rsi: { label: "RSI", color: "var(--color-up)" } }} className="h-[320px] w-full"><ComposedChart data={query.data?.points ?? []} margin={{ left: 4, right: 12 }}><CartesianGrid vertical={false} /><XAxis dataKey="date" tickLine={false} axisLine={false} /><YAxis yAxisId="price" tickLine={false} axisLine={false} /><YAxis yAxisId="osc" orientation="right" domain={[0, 100]} tickLine={false} axisLine={false} /><ChartTooltip content={<ChartTooltipContent />} /><Area yAxisId="osc" dataKey="volatility" fill="var(--color-primary)" fillOpacity={0.12} stroke="var(--color-primary)" /><Line yAxisId="price" dataKey="price" stroke="var(--color-accent)" strokeWidth={2} dot={false} /><Line yAxisId="osc" dataKey="rsi" stroke="var(--color-up)" strokeWidth={1.5} dot={false} /></ComposedChart></ChartContainer></PanelShell>; }

function PanelShell({ title, hint, children }: { title: string; hint: string; children: React.ReactNode }) { return <section className="panel p-4"><div className="mb-4 flex items-center justify-between"><div className="label-caps">{title}</div><span className="tape text-[10px] text-muted-foreground">{hint}</span></div>{children}</section>; }
