/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdvancedRouteImport } from './routes/advanced'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LeadersRouteImport } from './routes/leaders'
import { Route as SizingRouteImport } from './routes/sizing'
import { Route as AuthenticatedDeskRouteImport } from './routes/_authenticated/desk'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStrategiesRouteImport } from './routes/_authenticated/strategies'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiPublicHooksMonitorAlertsRouteImport } from './routes/api/public/hooks/monitor-alerts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedRoute = AdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadersRoute = LeadersRouteImport.update({
  id: '/leaders',
  path: '/leaders',
  getParentRoute: () => rootRouteImport,
} as any)
const SizingRoute = SizingRouteImport.update({
  id: '/sizing',
  path: '/sizing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDeskRoute = AuthenticatedDeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStrategiesRoute = AuthenticatedStrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiPublicHooksMonitorAlertsRoute =
  ApiPublicHooksMonitorAlertsRouteImport.update({
    id: '/api/public/hooks/monitor-alerts',
    path: '/api/public/hooks/monitor-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advanced': typeof AdvancedRoute
  '/auth': typeof AuthRouteWithChildren
  '/leaders': typeof LeadersRoute
  '/sizing': typeof SizingRoute
  '/desk': typeof AuthenticatedDeskRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/strategies': typeof AuthenticatedStrategiesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/public/hooks/monitor-alerts': typeof ApiPublicHooksMonitorAlertsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advanced': typeof AdvancedRoute
  '/auth': typeof AuthRouteWithChildren
  '/leaders': typeof LeadersRoute
  '/sizing': typeof SizingRoute
  '/desk': typeof AuthenticatedDeskRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/strategies': typeof AuthenticatedStrategiesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/public/hooks/monitor-alerts': typeof ApiPublicHooksMonitorAlertsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/advanced': typeof AdvancedRoute
  '/auth': typeof AuthRouteWithChildren
  '/leaders': typeof LeadersRoute
  '/sizing': typeof SizingRoute
  '/_authenticated/desk': typeof AuthenticatedDeskRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/strategies': typeof AuthenticatedStrategiesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/public/hooks/monitor-alerts': typeof ApiPublicHooksMonitorAlertsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advanced'
    | '/auth'
    | '/leaders'
    | '/sizing'
    | '/desk'
    | '/settings'
    | '/strategies'
    | '/auth/callback'
    | '/api/public/hooks/monitor-alerts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advanced'
    | '/auth'
    | '/leaders'
    | '/sizing'
    | '/desk'
    | '/settings'
    | '/strategies'
    | '/auth/callback'
    | '/api/public/hooks/monitor-alerts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/advanced'
    | '/auth'
    | '/leaders'
    | '/sizing'
    | '/_authenticated/desk'
    | '/_authenticated/settings'
    | '/_authenticated/strategies'
    | '/auth/callback'
    | '/api/public/hooks/monitor-alerts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdvancedRoute: typeof AdvancedRoute
  AuthRoute: typeof AuthRouteWithChildren
  LeadersRoute: typeof LeadersRoute
  SizingRoute: typeof SizingRoute
  ApiPublicHooksMonitorAlertsRoute: typeof ApiPublicHooksMonitorAlertsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced': {
      id: '/advanced'
      path: '/advanced'
      fullPath: '/advanced'
      preLoaderRoute: typeof AdvancedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaders': {
      id: '/leaders'
      path: '/leaders'
      fullPath: '/leaders'
      preLoaderRoute: typeof LeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sizing': {
      id: '/sizing'
      path: '/sizing'
      fullPath: '/sizing'
      preLoaderRoute: typeof SizingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/desk': {
      id: '/_authenticated/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof AuthenticatedDeskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/strategies': {
      id: '/_authenticated/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof AuthenticatedStrategiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/public/hooks/monitor-alerts': {
      id: '/api/public/hooks/monitor-alerts'
      path: '/api/public/hooks/monitor-alerts'
      fullPath: '/api/public/hooks/monitor-alerts'
      preLoaderRoute: typeof ApiPublicHooksMonitorAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDeskRoute: typeof AuthenticatedDeskRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStrategiesRoute: typeof AuthenticatedStrategiesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDeskRoute: AuthenticatedDeskRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStrategiesRoute: AuthenticatedStrategiesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdvancedRoute: AdvancedRoute,
  AuthRoute: AuthRouteWithChildren,
  LeadersRoute: LeadersRoute,
  SizingRoute: SizingRoute,
  ApiPublicHooksMonitorAlertsRoute: ApiPublicHooksMonitorAlertsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
